In [1]:
#importing necessary libraries
import pandas as pd
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [9]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [10]:
rewards_all_episodes = []

In [11]:
#Q-learning algorithm
for episodes in range(num_episodes):
  state = env.reset()

  done = False
  rewards_current_episode = 0 

  for step in range(max_steps_per_episode):

    #exploration-exploitation trade-off
    exploration_rate_threshold = random.uniform(0,1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action = env.action_space.sample()
    
    new_state, reward, done, info = env.step(action)

    #updating the Q-table
    q_table[state,action] = q_table[state,action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state,:]))

    state = new_state
    rewards_current_episode += reward

    if done == True:
      break

  #exploration-rate-decay
  exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episodes)

  rewards_all_episodes.append(rewards_current_episode)

#calculate and print the average reward per 1000 episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("*********Average Reward Per 1000 episodes***********")
for r in rewards_per_thousand_episodes:
  print(count,": ",str(sum(r/1000)))
  count += 1000

#printing the Q-table
print("\n\************Q-table************")
print(q_table)

<>:42: DeprecationWarning: invalid escape sequence '\*'


*********Average Reward Per 1000 episodes***********
1000 :  0.05000000000000004
2000 :  0.21200000000000016
3000 :  0.4130000000000003
4000 :  0.5720000000000004
5000 :  0.6180000000000004
6000 :  0.6490000000000005
7000 :  0.6680000000000005
8000 :  0.6980000000000005
9000 :  0.6640000000000005
10000 :  0.6860000000000005

\************Q-table************
[[0.55469163 0.50827717 0.49842194 0.50853143]
 [0.35120819 0.29639506 0.34553113 0.50910433]
 [0.43038917 0.38604474 0.41536857 0.46905262]
 [0.26418569 0.30082694 0.22037475 0.43657961]
 [0.56804102 0.34259636 0.23915315 0.46060297]
 [0.         0.         0.         0.        ]
 [0.35575986 0.08729044 0.21731094 0.12130153]
 [0.         0.         0.         0.        ]
 [0.38959657 0.38404244 0.35352849 0.59898466]
 [0.48863941 0.64328416 0.3705454  0.45829787]
 [0.67183466 0.39461989 0.36819177 0.31284579]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41630219 0.56632484 0.778